name = "OscarHomotopyContinuation"
uuid = "c41f96c7-3954-4cb9-9eff-e5f7ee76eb29"
authors = ["Tobias Boege <post@taboege.de>"]
version = "0.1.0"

[deps]
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
HomotopyContinuation = "^2.9.2"
Oscar = "^1.0"
